#!/usr/bin/env python3
"""Extract the strict-main CellOracle data needed by the Figure 2B R plot.

This script does not modify the source h5ad.  It writes a small metadata table
and a sparse count matrix so the downstream plotting and t-SNE calculation are
performed in R.
"""

from __future__ import annotations

import argparse
import gzip
import json
from pathlib import Path

import anndata as ad
import numpy as np
import pandas as pd
from scipy.io import mmwrite
from scipy.sparse import csr_matrix


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = PROJECT_ROOT / "data/processed/driver/celloracle_module6_6/celloracle_module6_6_input.h5ad"
DEFAULT_OUT_DIR = PROJECT_ROOT / "metadata/driver/figure2b_sox4"


def as_bool(values: pd.Series) -> pd.Series:
    if pd.api.types.is_bool_dtype(values):
        return values.fillna(False)
    return values.astype(str).str.lower().isin({"true", "1", "yes", "y"})


def write_matrix_gz(matrix, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with gzip.open(path, "wb") as handle:
        mmwrite(handle, csr_matrix(matrix))


def run(input_h5ad: Path, out_dir: Path, pseudotime_column: str) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)
    adata = ad.read_h5ad(input_h5ad)
    required = {
        "driver_main_strict__eligible",
        pseudotime_column,
        "celloracle_state",
    }
    missing = sorted(required.difference(adata.obs.columns))
    if missing:
        raise ValueError(f"Missing required h5ad obs columns: {missing}")
    if "X_celloracle_umap" not in adata.obsm:
        raise ValueError("X_celloracle_umap is required")
    if "counts" not in adata.layers:
        raise ValueError("counts layer is required for R t-SNE")

    pseudotime = pd.to_numeric(adata.obs[pseudotime_column], errors="coerce")
    mask = as_bool(adata.obs["driver_main_strict__eligible"]) & pseudotime.notna()
    if int(mask.sum()) < 100:
        raise ValueError("Too few strict-main cells for Figure 2B")

    selected = adata[mask.to_numpy()].copy()
    selected_pt = pd.to_numeric(selected.obs[pseudotime_column], errors="raise")
    embedding = np.asarray(selected.obsm["X_celloracle_umap"], dtype=float)
    cells = pd.DataFrame(
        {
            "cell_id": selected.obs_names.astype(str),
            "celloracle_state": selected.obs["celloracle_state"].astype(str).to_numpy(),
            "umap_1": embedding[:, 0],
            "umap_2": embedding[:, 1],
            "pseudotime": selected_pt.to_numpy(dtype=float),
        }
    )
    cells.to_csv(out_dir / "figure2b_sox4_cells.tsv.gz", sep="\t", index=False, compression="gzip")
    write_matrix_gz(selected.layers["counts"], out_dir / "figure2b_sox4_counts.mtx.gz")
    pd.DataFrame({"gene": selected.var_names.astype(str)}).to_csv(
        out_dir / "figure2b_sox4_genes.tsv.gz", sep="\t", index=False, compression="gzip"
    )

    state_counts = cells["celloracle_state"].value_counts().sort_index().to_dict()
    report = {
        "module": "Figure 2B",
        "analysis": "SOX4 baseline developmental vector field",
        "input_h5ad": str(input_h5ad.resolve()),
        "pseudotime_column": pseudotime_column,
        "cell_filter": "driver_main_strict__eligible == TRUE and pseudotime is non-null",
        "n_source_cells": int(adata.n_obs),
        "n_selected_cells": int(len(cells)),
        "n_genes": int(selected.n_vars),
        "state_counts": {str(k): int(v) for k, v in state_counts.items()},
        "outputs": {
            "cells": str((out_dir / "figure2b_sox4_cells.tsv.gz").resolve()),
            "counts": str((out_dir / "figure2b_sox4_counts.mtx.gz").resolve()),
            "genes": str((out_dir / "figure2b_sox4_genes.tsv.gz").resolve()),
        },
        "note": "Source h5ad was read only; UMAP/vector field/t-SNE are generated by the R plotting script.",
    }
    (out_dir / "figure2b_sox4_data_report.json").write_text(
        json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    return report


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-h5ad", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument(
        "--pseudotime-column",
        default="driver_main_strict__pseudotime_rank",
    )
    args = parser.parse_args()
    report = run(args.input_h5ad, args.out_dir, args.pseudotime_column)
    print(json.dumps(report, ensure_ascii=False))


if __name__ == "__main__":
    main()
