#!/usr/bin/env Rscript

root <- normalizePath(file.path(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1])), ".."), winslash = "/", mustWork = TRUE)
source(file.path(root, "scripts", "figure5_temporal_core.R"))
source(file.path(root, "scripts", "figure5_plot_theme.R"))
paths <- figure5_paths(root)

checks <- list()
add_check <- function(id, check, status, evidence, critical = TRUE) {
  checks[[id]] <<- data.table(check_id = id, check = check, status = status, critical = critical, evidence = evidence)
}

plot_scripts <- list.files(file.path(root, "scripts"), pattern = "^plot_figure5.*\\.R$", full.names = TRUE)
plot_text <- paste(unlist(lapply(plot_scripts, readLines, warn = FALSE)), collapse = "\n")
add_check(1, "All formal figures are generated by R", if (length(plot_scripts) >= 8) "PASS" else "FAIL", paste(basename(plot_scripts), collapse = ";"))
add_check(2, "No Python plotting output enters formal directories", if (!grepl("matplotlib|seaborn|scanpy\\.pl|pandas\\.plot", plot_text, ignore.case = TRUE)) "PASS" else "FAIL", "Figure 5 plot scripts scanned")
add_check(3, "All panels source the ggsci Lancet theme", if (all(vapply(plot_scripts, function(f) any(grepl("figure5_plot_theme.R", readLines(f, warn = FALSE), fixed = TRUE)), logical(1)))) "PASS" else "FAIL", "shared theme source audit")
add_check(4, "Axis A is Lancet blue", if (axis_palette[["identity_loss"]] == lancet_palette[[1]]) "PASS" else "FAIL", axis_palette[["identity_loss"]])
add_check(5, "Axis B is Lancet green", if (axis_palette[["stress_transition"]] == lancet_palette[[3]]) "PASS" else "FAIL", axis_palette[["stress_transition"]])
add_check(6, "Axis C is Lancet red", if (axis_palette[["sox4_stabilization"]] == lancet_palette[[2]]) "PASS" else "FAIL", axis_palette[["sox4_stabilization"]])
add_check(7, "Diverging scale is centered on neutral white", if (figure5_diverging_palette[[3]] == "#F7F7F7") "PASS" else "FAIL", paste(figure5_diverging_palette, collapse = ";"))
add_check(8, "No default discrete palette in formal plot scripts", if (grepl("scale_(colour|fill)_manual", plot_text)) "PASS" else "FAIL", "manual scales present")
add_check(9, "Forbidden palettes are absent", if (!grepl("viridis|rainbow|\\bjet\\b", plot_text, ignore.case = TRUE)) "PASS" else "FAIL", "plot-script scan")

audit_path <- file.path(paths$metadata, "figure5_frozen_signature_audit.tsv")
audit <- if (file.exists(audit_path)) fread(audit_path) else data.table()
add_check(10, "Figure 5 uses frozen signatures", if (nrow(audit) && all(grepl("Figure|predefined", audit$source_figure))) "PASS" else "FAIL", paste(unique(audit$source), collapse = ";"))
add_check(11, "No pseudotime-based favorable gene selection", if (nrow(audit) && all(grepl("no pseudotime|frozen|present in both", audit$selection_rule, ignore.case = TRUE))) "PASS" else "FAIL", "signature selection rules")
score_path <- file.path(paths$metadata, "figure5_three_axis_cell_scores.tsv.gz")
scores <- if (file.exists(score_path)) fread(score_path, select = c("identity_program_score_original", "identity_loss_score_raw"), showProgress = FALSE) else data.table()
add_check(12, "Identity-loss direction is correct", if (nrow(scores) && abs(cor(scores$identity_program_score_original, scores$identity_loss_score_raw, use = "complete.obs") + 1) < 1e-6) "PASS" else "FAIL", "cor(original identity, raw identity loss)=-1")
orientation <- fread(file.path(paths$metadata, "figure5_pseudotime_orientation_audit.tsv"))
add_check(13, "Pseudotime direction is audited and unified", if (all(orientation[status == "Available"]$oriented_score >= 0)) "PASS" else "FAIL", paste(orientation$method, orientation$flipped, sep = "=", collapse = ";"))
gam_summary <- fread(file.path(paths$metadata, "figure5b_gam_model_summary.tsv"))
add_check(14, "Formal statistics use patient/sample units", if (all(gam_summary[scenario == "primary" & status == "fitted"]$n_patients >= 2)) "PASS" else "FAIL", "patient-pseudobulk GAM")
boot_report <- jsonlite::read_json(file.path(paths$metadata, "figure5_bootstrap_temporal_landmarks_report.json"), simplifyVector = TRUE)
add_check(15, "Bootstrap does not treat cells as patients", if (identical(boot_report$resampling_cells_as_independent_units, FALSE)) "PASS" else "FAIL", paste0("unit=", boot_report$bootstrap_unit))
manifest <- fread(file.path(paths$metadata, "figure5c_heatmap_gene_manifest.tsv"))
add_check(16, "Figure 5C genes come from frozen manifest", if (nrow(manifest) && all(manifest$source %chin% audit$source)) "PASS" else "FAIL", paste0("n=", nrow(manifest)))
ddata <- fread(file.path(paths$metadata, "figure5d_temporal_landmarks_plot_data.tsv"))
add_check(17, "Figure 5D landmarks have 95% CI", if (nrow(ddata) && all(is.finite(ddata$lower) & is.finite(ddata$upper))) "PASS" else "FAIL", paste0("rows=", nrow(ddata)))
edata <- fread(file.path(paths$metadata, "figure5e_precedence_probabilities.tsv"))
add_check(18, "Figure 5E probabilities come from bootstrap", if (nrow(edata) && all(edata$n_bootstrap_effective > 0)) "PASS" else "FAIL", paste0("max n=", max(edata$n_bootstrap_effective)))
fdata <- fread(file.path(paths$metadata, "figure5f_method_concordance.tsv"))
add_check(19, "Missing methods are marked Not available", if (all(fdata[method %chin% c("DPT", "CellRank pseudotime")]$status == "Not available")) "PASS" else "FAIL", "DPT; CellRank pseudotime")
gmeta <- fread(file.path(paths$metadata, "figure5g_patient_meta_analysis.tsv"))
add_check(20, "Random-effects meta-analysis ran", if (any(gmeta$status == "fitted")) "PASS" else "WARN", paste0("fitted rows=", sum(gmeta$status == "fitted")), critical = FALSE)
hreport <- jsonlite::read_json(file.path(paths$metadata, "figure5h_overlapping_phase_model_report.json"), simplifyVector = TRUE)
add_check(21, "Figure 5H is generated from results", if (isTRUE(hreport$axis_boundaries_from_bootstrap)) "PASS" else "FAIL", "bootstrap-derived boundaries")
hsummary <- fread(file.path(paths$metadata, "figure5h_activity_band_summary.tsv"))
add_check(26, "Figure 5H formal starts exclude boundary-sensitive onset_time", if (all(hsummary$boundary_start > hsummary$onset_bootstrap_median)) "PASS" else "FAIL", paste(hsummary$boundary_start, collapse = ";"))
add_check(27, "Figure 5H uses stable t10 or directional activation fallback", if (all(hsummary$boundary_method %chin% c("bootstrap_t10", "directional_activation_fallback")) && all(is.finite(hsummary$t10))) "PASS" else "FAIL", paste(hsummary$boundary_method, collapse = ";"))
htext <- paste(readLines(file.path(root, "scripts", "plot_figure5h_overlapping_phase_model.R"), warn = FALSE), collapse = "\n")
add_check(28, "Figure 5H uses alpha-gradient polygons, fades, and no stage rectangles", if (grepl("geom_polygon", htext, fixed = TRUE) && grepl("scale_alpha_identity", htext, fixed = TRUE) && grepl("fade_end", htext, fixed = TRUE) && !grepl("geom_rect", htext, fixed = TRUE)) "PASS" else "FAIL", "continuous activity-band rendering")
add_check(29, "Figure 5H caption states bands are not discrete events", if (identical(hreport$caption, "Activity bands represent relative programme prominence derived from smoothed scores and bootstrap temporal landmarks; they do not indicate discrete activation or termination events.")) "PASS" else "FAIL", "caption audit")
add_check(30, "Figure 5H retains t50 and maximum-slope markers", if (all(is.finite(hsummary$t50) & is.finite(hsummary$maximum_slope))) "PASS" else "FAIL", "core temporal markers")

panel_bases <- c(
  file.path(paths$figures, "figure5a_temporal_framework/figure5a_temporal_framework"),
  file.path(paths$figures, "figure5b_three_axis_gam/figure5b_three_axis_gam_main"),
  file.path(paths$figures, "figure5c_temporal_heatmap/figure5c_temporal_heatmap"),
  file.path(paths$figures, "figure5d_temporal_landmarks/figure5d_temporal_landmarks"),
  file.path(paths$figures, "figure5e_precedence_matrix/figure5e_precedence_matrix"),
  file.path(paths$figures, "figure5f_method_concordance/figure5f_method_concordance"),
  file.path(paths$figures, "figure5g_patient_temporal_forest/figure5g_patient_temporal_forest"),
  file.path(paths$figures, "figure5h_overlapping_phase_model/figure5h_overlapping_phase_model")
)
formal_files <- as.vector(outer(panel_bases, c(".pdf", ".png", ".svg", ".tiff"), paste0))
existing <- file.exists(formal_files) & file.info(formal_files)$size > 0
add_check(22, "All PDF, PNG, SVG and TIFF files exist and are non-empty", if (all(existing)) "PASS" else "FAIL", paste0(sum(existing), "/", length(existing)))
theme_text <- paste(readLines(file.path(root, "scripts", "figure5_plot_theme.R"), warn = FALSE), collapse = "\n")
add_check(23, "PNG/TIFF export contract is 600 dpi with TIFF LZW", if (grepl("dpi = 600", theme_text) && grepl("compression = \"lzw\"", theme_text)) "PASS" else "FAIL", "shared export function source")
add_check(24, "Fixed random seeds are recorded", if (all(c(20260805) %in% unique(as.integer(boot_report$random_seed)))) "PASS" else "FAIL", paste0("seed=", boot_report$random_seed))

baseline_path <- file.path(paths$metadata, "figure5_figure1_4_baseline.tsv")
baseline <- fread(baseline_path)
current_exists <- file.exists(baseline$file_path)
current_md5 <- rep(NA_character_, nrow(baseline)); current_md5[current_exists] <- unname(tools::md5sum(baseline$file_path[current_exists]))
unchanged <- current_exists & current_md5 == baseline$md5
add_check(25, "Figure 1-4 files are unchanged", if (all(unchanged)) "PASS" else "FAIL", paste0(sum(unchanged), "/", nrow(baseline), " baseline files unchanged"))

validation <- rbindlist(checks)
figure5_write_tsv(validation, file.path(paths$metadata, "figure5_validation_report.tsv"))
overall <- if (any(validation$status == "FAIL")) "FAIL" else if (any(validation$status == "WARN")) "PASS_WITH_REVIEW_RISKS" else "PASS"
figure5_write_json(list(overall_status = overall, checks = split(validation, seq_len(nrow(validation))),
                        sci_main_figure_status = if (overall == "PASS") "meets technical SCI main-figure standard" else if (overall == "PASS_WITH_REVIEW_RISKS") "technically complete with stated review risks" else "does not yet meet standard"),
                   file.path(paths$metadata, "figure5_validation_report.json"))
if (any(validation$status == "FAIL")) stop("Figure 5 validation failed: ", paste(validation[status == "FAIL"]$check_id, collapse = ","))
message("Figure 5 validation: ", overall)
